### ISSUE TITLE
Query results wrong when index is used

### ISSUE THREAD

**Issue by don-tay** [don-tay/simpledb#5]
Under working branch for #4 , when a table is queried with a predicate that makes use of the index, the query results returns no rows all the time. #4 uses the improved planners - `HeuristicQueryPlanner` and `IndexUpdatePlanner`

Steps to replicate:
1. Delete existing `studentdb` directory.
2. Run `test/CreateStudentDB` to re-create studentdb with populated data and an index on `Student(sid)`
3. Run database with `test/SimpleIJ`.
4. Run the following DDL to confirm table is populated: `SELECT sid, sname from student`
5. Run any DDLs that makes use of the index on Student(sid)
Eg.
`SELECT sid, sname from student where sid = 1`
`SELECT sid, sname from student where sid <> 0`
`SELECT sid, sname from student where sid < 10`
`SELECT sid, sname from student where sid > 5`

**Comment by don-tay** [comment]
I believe this is not a regression caused by the inequality feature. 

I have tried checking out to the commit before the inequality feature `git checkout 3246e39` and repeating the above steps. The issue still persists.

**Comment by tishyakhanna97** [comment]
I was able to reproduce the bug above

**Comment by don-tay** [comment]
Currently, the query works for equality operators, but not for inequality ones.

```
SQL> select sid,sname from student where sid<=5
index on sid used
 sid sname
----------
  5  bob

SQL> select sid,sname from student where sid>5
index on sid used
 sid sname
----------

SQL> select sid,sname from student where sid<5
index on sid used
 sid sname
----------

SQL> select sid,sname from student where sid<=5
index on sid used
 sid sname
----------
  5  bob

SQL> select sid,sname from student where sid<>5
index on sid used
 sid sname
----------

SQL> select sid,sname from student where sid=5
index on sid used
 sid sname
----------
  5  bob
```

**Comment by xinyee20** [comment]
Inequality query works fine for code before indexing was implemented so operator functions doesn't seem to be the problem. 

Attempts:
- Adjusting the commands to be more precise -> Issue persists on inequality queries. 
- Creating index using MajorId on STUDENT table and running the test files -> Valid results are produced so indexing seems to be working. 

More digging needs to be done to find out where the issue lies.

**Comment by don-tay** [comment]
I suspect that the logic involved is found in `simpledb/index/query/IndexSelectScan.java`
https://github.com/don-tay/simpledb/blob/36514a491698ce9c1df7426092778c07f013037d/src/simpledb/index/query/IndexSelectScan.java#L50

The analogous file involved for a full table scan is found in `simpledb/query/SelectScan.java`
https://github.com/don-tay/simpledb/blob/36514a491698ce9c1df7426092778c07f013037d/src/simpledb/query/SelectScan.java#L35

**Comment by xinyee20** [comment]
The idx.next() within the next() in IndexSelectScan.java uses the next() of the selected Index. It will adjust the implementation according to the index type that is chosen so there's no need to update that method.

**Comment by don-tay** [comment]
Closing this issue since it is not in scope for simpledb+, we can KIV and follow up if necessary in the future.
