### ISSUE TITLE
Sorting cost is wrong

### ISSUE THREAD

**Issue by tishyakhanna97** [don-tay/simpledb#51]
We seem to be outputting negative/very low sorting costs, and this leads to the preference of the sortjoin over other joins

**Comment by don-tay** [comment]
Do you have a list of queries for which this is happening?

**Comment by tishyakhanna97** [comment]
@don-tay 
`select sid,sname,dname,title,grade from student,dept,course,enroll where sid=studentid and deptid=did and majorid=did`
`select sid, grade from enroll, student where sid=studentid`
